-- Snowflake Database Setup for Financial Data Service
-- Story 1.1: Set up Snowflake Environment

-- Create Database
CREATE DATABASE IF NOT EXISTS EQUITY_DATA;

-- Use the database
USE DATABASE EQUITY_DATA;

-- Create warehouse if it doesn't exist
CREATE WAREHOUSE IF NOT EXISTS EQUITY_LOAD_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- Create roles for access control
CREATE ROLE IF NOT EXISTS EQUITY_DATA_LOADER;
CREATE ROLE IF NOT EXISTS EQUITY_DATA_READER;

-- Grant privileges
GRANT USAGE ON DATABASE EQUITY_DATA TO ROLE EQUITY_DATA_LOADER;
GRANT USAGE ON DATABASE EQUITY_DATA TO ROLE EQUITY_DATA_READER;
GRANT USAGE ON WAREHOUSE EQUITY_LOAD_WH TO ROLE EQUITY_DATA_LOADER;
GRANT USAGE ON WAREHOUSE EQUITY_LOAD_WH TO ROLE EQUITY_DATA_READER;

-- Grant role to current user (replace with actual username)
-- GRANT ROLE EQUITY_DATA_LOADER TO USER <your_username>;
-- GRANT ROLE EQUITY_DATA_READER TO USER <your_username>;