-- Snowflake Schema Setup for Financial Data Service
-- Story 1.1: Set up Snowflake Environment

USE DATABASE EQUITY_DATA;

-- Create schemas
CREATE SCHEMA IF NOT EXISTS RAW_DATA;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Grant schema privileges to roles
GRANT ALL PRIVILEGES ON SCHEMA RAW_DATA TO ROLE EQUITY_DATA_LOADER;
GRANT USAGE ON SCHEMA RAW_DATA TO ROLE EQUITY_DATA_READER;

GRANT ALL PRIVILEGES ON SCHEMA STAGING TO ROLE EQUITY_DATA_LOADER;
GRANT USAGE ON SCHEMA STAGING TO ROLE EQUITY_DATA_READER;

GRANT ALL PRIVILEGES ON SCHEMA ANALYTICS TO ROLE EQUITY_DATA_LOADER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE EQUITY_DATA_READER;

-- Create File Format for JSON data
CREATE OR REPLACE FILE FORMAT RAW_DATA.JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    ENABLE_OCTAL = FALSE
    ALLOW_DUPLICATE = FALSE
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = FALSE
    IGNORE_UTF8_ERRORS = FALSE;